insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Training', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Accounting', true);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', true);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Product Management', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Product Management', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Human Resources', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Support', true);
insert into BookCategory (Name, IsActive) values ('Sales', true);
insert into BookCategory (Name, IsActive) values ('Engineering', true);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Business Development', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Services', false);
insert into BookCategory (Name, IsActive) values ('Sales', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Support', false);
insert into BookCategory (Name, IsActive) values ('Services', true);
insert into BookCategory (Name, IsActive) values ('Marketing', false);
insert into BookCategory (Name, IsActive) values ('Accounting', false);
insert into BookCategory (Name, IsActive) values ('Training', false);
insert into BookCategory (Name, IsActive) values ('Legal', false);
insert into BookCategory (Name, IsActive) values ('Marketing', true);
insert into BookCategory (Name, IsActive) values ('Business Development', true);
insert into BookCategory (Name, IsActive) values ('Research and Development', false);
insert into BookCategory (Name, IsActive) values ('Legal', true);
insert into BookCategory (Name, IsActive) values ('Engineering', false);
insert into BookCategory (Name, IsActive) values ('Research and Development', true);
